# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Update Experiments

on:
  push:
    branches: [ master ]
  schedule:
    - cron: "0 * * * *"
    
permissions:
  contents: write

jobs:
  experiments:
    runs-on: ubuntu-latest
    env:
      DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
      ONE_TIME_FETCH: ${{ secrets.ONE_TIME_FETCH }}

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    # Check out repository under $GITHUB_WORKSPACE, so the job can access it
    - uses: actions/checkout@v3

    # Set up node.js
    - name: Set up Node.JS
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    # Install dependencies
    - name: Install dependencies
      run: |
        sudo apt-get install xvfb
        npm install
    
    - name: Fetch experiments
      run: |
        node action.js

  user-experiment-rollouts:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Calculate (1)
      run: |
        node rollout-calculation.js
      
    - name: Calculate (2)
      run: |
        node rollout-calculation.js
      
    - name: Calculate (3)
      run: |
        node rollout-calculation.js
      
    - name: Calculate (4)
      run: |
        node rollout-calculation.js
      
    - name: Calculate (5)
      run: |
        node rollout-calculation.js
      
    - name: Calculate (6)
      run: |
        node rollout-calculation.js
      
    - name: Calculate (7)
      run: |
        node rollout-calculation.js
      
    - name: Calculate (8)
      run: |
        node rollout-calculation.js
      
    - name: Calculate (9)
      run: |
        node rollout-calculation.js
      
    - name: Calculate (10)
      run: |
        node rollout-calculation.js

  update:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Update user experiments
      run: |
        node average-rollouts.js

  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    # Commit all changed files to the repository
    - name: Commit to the repo
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m 'Update experiments.json' || true
        git push
