# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Update Experiments

on:
  push:
    branches: [ master ]
  schedule:
    - cron: "0 */6 * * *"
    
permissions:
  contents: write

jobs:
  experiments:
    runs-on: ubuntu-latest
    env:
      DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
      ONE_TIME_FETCH: ${{ secrets.ONE_TIME_FETCH }}

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.JS
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: |
        sudo apt-get install xvfb
        npm install
    
    - name: Fetch experiments
      run: |
        node action.js
    
    - uses: actions/upload-artifact@v2
      with:
        name: experiments
        path: ./

  user-experiment-rollouts:
    needs: experiments
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3

    - run: rm experiments.json

    - uses: actions/download-artifact@v2
      with:
        name: experiments

    - name: Set up Node.JS
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: |
        sudo apt-get install xvfb
        npm install

    - name: Calculate
      run: |
        node rollout-calculation.js &
        node rollout-calculation.js &
        node rollout-calculation.js &
        node rollout-calculation.js &
        node rollout-calculation.js &
        node rollout-calculation.js &
        node rollout-calculation.js &
        node rollout-calculation.js &
        node rollout-calculation.js &
        node rollout-calculation.js &
        wait

    - uses: actions/upload-artifact@v2
      with:
        name: user-experiments
        path: ./

  update:
    needs: [experiments, user-experiment-rollouts]
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3

    - run: rm experiments.json

    - uses: actions/download-artifact@v2
      with:
        name: experiments

    - run: rm user-experiments.json

    - uses: actions/download-artifact@v2
      with:
        name: user-experiments

    - name: Set up Node.JS
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: |
        sudo apt-get install xvfb
        npm install

    - name: Update user experiments
      run: |
        node average-rollouts.js

    - uses: actions/upload-artifact@v2
      with:
        name: experiments
        path: ./

  deploy:
    needs: [experiments, user-experiment-rollouts, update]
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3

    - run: rm experiments.json

    - uses: actions/download-artifact@v2
      with:
        name: experiments

    - name: Set up Node.JS
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: |
        sudo apt-get install xvfb
        npm install

    - name: Commit to the repo
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m 'Update experiments.json' || true
        git push
